### ISSUE TITLE
[가게정보] 백엔드 에러시나리오 처리

### ISSUE THREAD

**Issue by urbanscenery** [wwh-techcamp-2018/team8-AOA2#22]

**Comment by nigayo** [comment]
label을 만든건 잘 했네요. 
milestone도 좋아요. 

이 task(feature)가 어떤일인지는 팀이 잘 알거 같긴한데요.
그런 설명을 넣으면 더 좋을 듯.

등록자가 담당자인가요? assignees 도 활용해보세요~
